dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: prod
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: test16
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: test17
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
